org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=384m -XX:+HeapDumpOnOutOfMemoryError -Dkotlin.daemon.jvm.options=-Xmx1024m
org.gradle.daemon=false
org.gradle.workers.max=2
org.gradle.parallel=false
org.gradle.configureondemand=false
android.useAndroidX=true
android.enableJetifier=true
kotlin.incremental=false
kotlin.incremental.android=false
kotlin.caching.enabled=false
